### ISSUE TITLE
Why didn't I see the plugin load after loading the demo?

### ISSUE THREAD

**Issue by Linkea** [MizunagiKB/gd_cubism#51] opened 2023-12-12 19:12 UTC
![image](https://github.com/MizunagiKB/gd_cubism/assets/20165535/3f354f70-da85-4619-8471-e2f819516756)
There's only one node. I can't load this plugin. It seems miss a .cfg and .gd file.
My environment is Windows 11, gitdot 4.2.
The Latest CubismSdkForNative-5-r.1-beta.3 is also in thirdparty folder.

**Comment by Linkea** [comment] 2023-12-12 19:14
![image](https://github.com/MizunagiKB/gd_cubism/assets/20165535/21d18ea7-e605-44ca-bc1d-fa3aefcf53f6)
There is the error report.

**Comment by MizunagiKB** [comment] 2023-12-12 22:36
Thank you for reporting the issue.

You mentioned that the add-on is not loading properly. Could you please provide more details about the situation?

Firstly, I would like to know about the development environment you used for the build. GDCubism uses SCons for building, and the development environment you are using might be causing some errors. If there were any notifications that seemed like errors, I would like to know about them.

Even if the build appears to have been successful, depending on the environment, the load may fail at runtime. If it fails, an error will be displayed when the editor is launched. Is there anything displayed in this case?

**Comment by Linkea** [comment] 2023-12-13 09:01
Thank you for your reply.

I'm new to gotdot and still learning.
I configured it according to the document you provided. SCons is my first time to use it and I have also installed it. But I don't know how to use it, I don't know how to configure it.

The only error message so far is the one I sent. I find other plugins always with two files, .gd and .cfg. Maybe this is the reason I can't load this plugin. SCons is installed with the pip command. It should be the latest version. I'm not sure how to use it. The plug-in interface for project Settings is also blank. No plug-ins are displayed loaded.
Or where do I need to find other error messages to give you a full understanding of the situation?

Do I have to build by using SCons before loading this demo？Can you teach me how to do that step by step? 
I can't find the relevant document, sorry. I'm new to gotdot and I don't know much about it.

Thanks.

**Comment by MizunagiKB** [comment] 2023-12-13 23:43
It appears that SCons is already installed, so please proceed with the installation of Visual Studio. The free version of Visual Studio is acceptable, but it must be version 2019 or later.

Please ensure the following conditions are met:

* Visual Studio 2019 or later is installed.
* gd_cubism has been cloned using git.
* CubismSdkForNative is placed in the appropriate location.
* SCons is ready for use.

Once you have confirmed the above, please do the following:

1. Open the command prompt and navigate to the location where you cloned gd_cubism using git.
2. Confirm that a file named SConstruct is present in that folder.
3. Execute the following commands:

```
scons platform=windows arch=x86_64 target=template_debug
scons platform=windows arch=x86_64 target=template_release
```

You can find the documentation on how to build GDCubism at the following location:

https://github.com/MizunagiKB/gd_cubism/blob/main/doc/BUILD.en.adoc

**Comment by Linkea** [comment] 2023-12-14 18:43
Thank you very much!! 

I followed your steps and installed VS2022 successfully. And I successfully set the Live2d model in GDCubismUserModel. 
But I can’t load the model on the texture of the sprite2D node. It doesn’t show the model.
There is my settings.
![image](https://github.com/MizunagiKB/gd_cubism/assets/20165535/b6837ca8-d88b-4205-aa02-9ba4db0b59f4)
![image](https://github.com/MizunagiKB/gd_cubism/assets/20165535/16bd6548-7d97-4397-b073-3aa5458e4113)
![image](https://github.com/MizunagiKB/gd_cubism/assets/20165535/d24808bf-4f7b-473b-9522-b030f79eac7d)
The option is empty. But my model is successfully displayed on GDCubismUserModel. Is it because my model file is too large? My model’s canvas size on live2d is 1080P, and the output size is 1/1 (2048px).

**Comment by Linkea** [comment] 2023-12-14 19:00
Thank you so much!!
I followed your steps to install VS2022 and it worked.
The Live2d model was successfully set up and loaded in the GDCubismUserModel.

However, after setting the two nodes GDCubismEffectEyeBlink and GDCubismEffectBreath, automatic breathing and blinking are not implemented.
![image](https://github.com/MizunagiKB/gd_cubism/assets/20165535/050912c2-0856-400e-b27d-dc0432b1a8e7)

There were no errors.

_____________

I know the problem, the demo model downloaded from the official website was successfully used and blinked and breathed.
Maybe my model didn't export the corresponding runtime script.

Thank you so much!!

**Comment by MizunagiKB** [comment] 2023-12-16 23:35
I’m glad to hear that Live2D is working in your environment.

The blinking-like effect processing seems to be a part of the Live2D structure, so please try adjusting it while referring to the samples.

As it appears to be resolved, I will close this issue. If you encounter any other problems, please feel free to create a new issue.

**Closed as completed** 2023-12-24 23:46 UTC
